---
- name: deploy nodejs application
  hosts: all
  become: true

  tasks:
    - name: install packages
      package:
        name: 
          - httpd
          - git
          - nodejs
        state: present

    - name: starting httpd service
      service:
        name: httpd
        state: started
        enabled: true

    - name: clone git repo
      ansible.builtin.git:
        repo: "https://github.com/SquareFace7/devops-final-project.git"
        dest: /tmp/my_game

    - name: install dependencies
      command: npm install
      args:
        chdir: /tmp/my_game/Game  # וודא שהנתיב לתיקיית המשחק נכון

    - name: build the project
      command: npm run build
      args:
        chdir: /tmp/my_game/Game

    - name: remove old files
      shell: rm -rf /var/www/html/*

    - name: copy build result to web root
      # בדרך כלל תיקיית ה-Build נקראת dist. אם היא נקראת אחרת, שנה כאן
      shell: cp -r /tmp/my_game/Game/dist/* /var/www/html/
