---
- name: integration of terraform and ansible
  hosts: all
  become: true  # מריץ את ההתקנות עם הרשאות מנהל

  tasks:
    - name: installing httpd
      package:
        name: httpd
        state: present

    - name: installing php
      package:
        name: php
        state: present

    - name: starting httpd service
      service:
        name: httpd
        state: started
        enabled: true

    - name: installing git
      package:
        name: git
        state: present

    - name: ensure web root exists
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: clone git repo to temp directory
      ansible.builtin.git:
        repo: "https://github.com/SquareFace7/devops-final-project.git"
        dest: /var/www/html/temp_repo

    - name: copy game content to web root
      shell: cp -r /var/www/html/temp_repo/Game/* /var/www/html/
